default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['MY_BUDGETING_DATABASE_USERNAME'] %>
  password: <%= ENV['MY_BUDGETING_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
